### ISSUE TITLE
Instructions on how to run with existing data

### ISSUE THREAD

**Issue by rmNULL** [swethasubramanian/LungCancerDetection#18]
## Installation and usage
1)  Install the requirements( file attached ) using `pip install -r requirements.txt`
[requirements.txt](https://github.com/swethasubramanian/LungCancerDetection/files/4521521/requirements.txt)

2)  From project directory
$ `cd  src/models/`
$ `python3 train.py`

* `visualize_model.py` or `predict_model.py`  can be run once the training data is generated.

## Extra steps for Python 3
1)  you may face issues with print being called without parens, please replace the usage of print with print()

2) In [visualize_model.py Line 69](https://github.com/swethasubramanian/LungCancerDetection/blob/36e7980a891089921d18993ea631c89035296e76/src/models/visualize_model.py#L69), 
replace `nfilt/4` with `nfilt//4` as we expect a int.

## Request to Author
Looking at the Above steps this guide may feel un necesarry, but i spent around 2 hours trying to get this working.  This would have saved a lot of time, if the requirements file was provided.

## Other notes
If anyone is willing to change and make a pull request, please do so and make it runnable from any directory, that will be better than `cd`ing to models before execution.

Due to laziness, i'm only  writing this short guide, sorry folks.

**Comment by sachin2912** [comment]
I found this error while running train.py 
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-5-099d049d61a3> in <module>
     28 model.fit(X_train_images, Y_train_labels, n_epoch = 70, shuffle=True,\
     29                         validation_set = (X_val_images, Y_val_labels), show_metric = True,\
---> 30 			batch_size = 96, snapshot_epoch = True, run_id = 'nodule3-classifier')
     31 model.save("nodule3-classifier.tfl")
     32 print("Network trained and saved as nodule2-classifier.tfl!")

C:\ProgramData\Anaconda3\lib\site-packages\tflearn\models\dnn.py in fit(self, X_inputs, Y_targets, n_epoch, validation_set, show_metric, batch_size, shuffle, snapshot_epoch, snapshot_step, excl_trainops, validation_batch_size, run_id, callbacks)
    182         # TODO: check memory impact for large data and multiple optimizers
    183         feed_dict = feed_dict_builder(X_inputs, Y_targets, self.inputs,
--> 184                                       self.targets)
    185         feed_dicts = [feed_dict for i in self.train_ops]
    186         val_feed_dicts = None

C:\ProgramData\Anaconda3\lib\site-packages\tflearn\utils.py in feed_dict_builder(X, Y, net_inputs, net_targets)
    281                 X = [X]
    282             for i, x in enumerate(X):
--> 283                 feed_dict[net_inputs[i]] = x
    284         else:
    285             # If a dict is provided

IndexError: list index out of range
