### ISSUE TITLE
IOError: File ../data/candidates.csv does not exist.

### ISSUE THREAD

**Issue by JenifferWuUCLA** [swethasubramanian/LungCancerDetection#2]
Hi,
    I have checked out the codes, and executed the command "python create_images.py train" under the folder "LungCancerDetection/src/data". But, it prompts, "IOError: File ../data/candidates.csv does not exist". Indeed, I cannot find the "candidates.csv" file in the project.
    So, could you pls help to give me some suggestions? Thanks!
![candidates csv error](https://cloud.githubusercontent.com/assets/25890017/26664082/938b397a-46c1-11e7-805c-6b102e3eb52b.png)

**Comment by swethasubramanian** [comment]
I think that code was used to generate training, validation and test set from original images in LUNA16 dataset. I have provided the resulting images in the repo. Just download those and run the model. If you wanted to generate your own images, then you might need to download the luna16 dataset and use that code to generate your own images.

**Comment by JenifferWuUCLA** [comment]
Hi,
    In candidates.csv file, there is a column named "class", whether it means the .mhd image has a pulmonary nodule (lung cancer) or not? Could you pls help to give me some suggestions? Thanks!
![candidates_csv](https://cloud.githubusercontent.com/assets/25890017/26811787/83982fa8-4aa6-11e7-91b7-f8a89f115d47.png)

**Comment by bundelesneha05** [comment]
I think , in Luna16 database(candidates.csv) they had given corresponding seriesuid  with world coordinates of the  nodule and non-nodule . also class is given whether nodule(1) or non nodule(0).
further information follow link given below,
https://luna16.grand-challenge.org/data/
Thanks!
