### ISSUE TITLE
list index out of range

### ISSUE THREAD

**Issue by AYadav01** [swethasubramanian/LungCancerDetection#3]
when i run 'create_image.py test' in the cmd prompt, i get an error sayin list index out of range. The error refers to the following line: self.ds = sitk.ReadImage(path[0])

**Comment by AYadav01** [comment]
can you explain where does the raw path in 'create_images.py' referring to.

**Comment by itcthienkhiem** [comment]
the same issue? how fix it?

**Comment by swethasubramanian** [comment]
The raw images are from Luna 16 database. You will need to download it and refer raw_image_path to it. Same with candidates.csv file. For reference I have already created test, train, and validation sets and uploaded the dataset in the repository here. You should be able to directly use it without running create_images.py script.

**Comment by bundelesneha05** [comment]
But I think , their is need for the train, test and val labels for training and prediction purpose.

**Comment by a56256324** [comment]
Did you run successfully through debugging? I encountered the same error as you when generating data. I hope to get your help. Thank you.
